version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "arn:aws:secretsmanager:us-east-1:839734283765:secret:Srini-POC-Github-t0UOOD:srini_poc_github"
phases:
  install:
    commands:
    - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    - unzip terraform_install.zip -d /usr/bin/
    - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - |
        enter="\n"
        tinit=$(terraform init)
        tplan=$(terraform plan)
        trigger=${CODEBUILD_WEBHOOK_TRIGGER}
        echo $trigger
        echo ${CODEBUILD_WEBHOOK_EVENT}
        if [ ${CODEBUILD_WEBHOOK_EVENT} == 'PUSH' ]; then
          PR=${CODEBUILD_WEBHOOK_EVENT}
          pr_num=echo $PR | cut -d "/" -f2
          echo $pr_num
        fi
        echo $pr_num
        output="#### Terraform Initialization 🖌 $enter$tinit"
        echo $output
        curl -X PATCH -H "Accept:application/vnd.github.v3+json" -H "Authorization:Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/srinin01/testcodebuild2/pulls/$pr_num" -d '{ "title": "hello" }'
        
      - echo build done!
