version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "arn:aws:secretsmanager:us-east-1:839734283765:secret:Srini-POC-Github-t0UOOD:srini_poc_github"
phases:
  install:
    commands:
    - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    - unzip terraform_install.zip -d /usr/bin/
    - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - |
        enter=$'\n'
        tplan=$(terraform plan)
        trigger=${CODEBUILD_WEBHOOK_TRIGGER}
        echo $trigger
        echo ${CODEBUILD_WEBHOOK_EVENT}
        if [[ $trigger == pr* ]]; then
          pr_num=${trigger#*/}
        fi  
        pr_num=4  
        echo $pr_num
        plan_str="#### Terraform Plan 🖌"
        echo $tplan
        pplan="aaaTerraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n  # aws_s3_bucket.sat_bucket will be created\n  + resource \"aws_s3_bucket\" \"sat_bucket\" {\n      + acceleration_status         = (known after apply)\n      + acl                         = \"private\"\n      + arn                         = (known after apply)\n      + bucket                      = \"sat-bucket-11-16-srini\"\n      + bucket_domain_name          = (known after apply)\n      + bucket_regional_domain_name = (known after apply)\n      + force_destroy               = false\n      + hosted_zone_id              = (known after apply)\n      + id                          = (known after apply)\n      + region                      = (known after apply)\n      + request_payer               = (known after apply)\n      + tags_all                    = (known after apply)\n      + website_domain              = (known after apply)\n      + website_endpoint            = (known after apply)\n\n      + versioning {\n          + enabled    = (known after apply)\n          + mfa_delete = (known after apply)\n        }\n    }\n\nPlan: 1 to add, 0 to change, 0 to destroy."
        if [[ -n "$pr_num" ]]; then
          curl -X PATCH -H "Accept:application/vnd.github.v3+json" -H "Authorization:Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/srinin01/test30/pulls/$pr_num" -d '{ "body": "$pplan"}'
        fi
      - echo build done!!
